#version 310 es
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (std430, binding = 0) buffer InputOutputBuffer {
    float data[];
} inputOutput;


void main() {
    uint id = (gl_NumWorkGroups.x * gl_WorkGroupID.y + gl_WorkGroupID.x);
    uint index = id * 7u;
    inputOutput.data[index + 0u] += inputOutput.data[index + 3u] / 50.0;
    inputOutput.data[index + 1u] += inputOutput.data[index + 4u] / 50.0;
    inputOutput.data[index + 2u] += inputOutput.data[index + 5u] / 50.0;
}